#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const assets = resolve(root, "src/assets");
const out = resolve(root, "src/generated-assets.ts");

const html = await readFile(resolve(assets, "index.html"), "utf8");
const css = await readFile(resolve(assets, "app.css"), "utf8");
const js = await readFile(resolve(assets, "app.js"), "utf8");

const escapeTemplate = (value) =>
  value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const body = `// Generated by apps/web/scripts/build-assets.mjs. Do not edit by hand.
// Source files live in apps/web/src/assets/.

export const INDEX_HTML = \`${escapeTemplate(html)}\`;

export const APP_CSS = \`${escapeTemplate(css)}\`;

export const APP_JS = \`${escapeTemplate(js)}\`;
`;

await writeFile(out, body, "utf8");
