// Generated by apps/web/scripts/build-assets.mjs. Do not edit by hand.
// Source files live in apps/web/src/assets/.

export const INDEX_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pact Dashboard</title>
    <link rel="stylesheet" href="/assets/app.css">
  </head>
  <body>
    <main class="shell">
      <header class="topbar">
        <div>
          <p class="eyebrow">pact v0.1</p>
          <h1>Authorization for company brains.</h1>
          <p class="lede">Sign in, connect sources, and keep agent access tied to identity and audit proof.</p>
        </div>
        <button id="logout" class="ghost hidden" type="button">Sign out</button>
      </header>
      <section id="loading" class="panel" aria-busy="true">
        <div class="panel-head">
          <span class="dots" aria-hidden="true"><span></span><span></span><span></span></span>
          <span>session</span>
          <span class="panel-meta">checking</span>
        </div>
        <div class="panel-body">
          <p class="terminal-line">awaiting workspace session...</p>
        </div>
      </section>
      <section id="login" class="panel hidden">
        <div class="panel-head">
          <span class="dots" aria-hidden="true"><span></span><span></span><span></span></span>
          <span>google login</span>
          <span class="panel-meta">workspace scoped</span>
        </div>
        <div class="panel-body login-grid">
          <div>
            <h2>Open a workspace.</h2>
            <p>Google proves the human. Pact mints workspace-scoped tokens for admin and audit surfaces.</p>
            <p id="oauth-help" class="notice hidden"></p>
          </div>
          <form id="login-form">
            <p id="workspace-summary" class="workspace-summary hidden"></p>
            <div id="workspace-field">
              <label for="workspace-id">workspace id</label>
              <input id="workspace-id" name="workspaceId" autocomplete="off" autocapitalize="none" spellcheck="false" inputmode="text" required aria-describedby="workspace-help" placeholder="00000000-0000-4000-8000-000000000000">
              <p id="workspace-help" class="help">Paste the UUID for the workspace you want to administer.</p>
            </div>
            <button id="login-submit" type="submit">Continue with Google</button>
          </form>
        </div>
      </section>
      <section id="dashboard" class="hidden">
        <div class="metrics">
          <article class="metric">
            <span class="label">workspace</span>
            <strong id="metric-workspace">-</strong>
          </article>
          <article class="metric">
            <span class="label">users</span>
            <strong id="metric-users">-</strong>
          </article>
          <article class="metric">
            <span class="label">drive</span>
            <strong id="metric-drive">checking</strong>
          </article>
          <article class="metric">
            <span class="label">audit</span>
            <strong id="metric-audit">checking</strong>
          </article>
        </div>
        <div class="grid">
          <article class="panel">
            <div class="panel-head"><span>identity</span><span class="panel-meta">signed session</span></div>
            <div class="panel-body"><dl id="session-details"></dl></div>
          </article>
          <article class="panel">
            <div class="panel-head"><span>google drive</span><span class="panel-meta">source</span></div>
            <div class="panel-body">
              <p id="drive-status">Checking connection...</p>
              <div class="row">
                <button id="drive-connect" type="button" aria-describedby="drive-help">Connect Drive</button>
                <button id="drive-disconnect" class="ghost hidden" type="button">Disconnect</button>
              </div>
              <p id="drive-help" class="help">Connect the signed-in Google account with read-only Drive access.</p>
            </div>
          </article>
          <article class="panel wide">
            <div class="panel-head"><span>drive retrieval</span><span class="panel-meta">index + search</span></div>
            <div class="panel-body">
              <div class="retrieval-grid">
                <section>
                  <div class="row">
                    <button id="drive-files-refresh" class="ghost" type="button">Load files</button>
                    <button id="drive-index" type="button" disabled>Index selected</button>
                  </div>
                  <label for="drive-files" class="select-label">Drive files</label>
                  <select id="drive-files" disabled>
                    <option value="">Connect Drive and load files</option>
                  </select>
                  <p id="drive-index-result" class="help">Index one Google Drive file before searching.</p>
                </section>
                <section>
                  <form id="drive-search-form" class="search-form">
                    <label for="drive-search-query">Search indexed context</label>
                    <div class="row">
                      <input id="drive-search-query" name="query" autocomplete="off" spellcheck="false" placeholder="customer notes, roadmap, contract terms">
                      <button id="drive-search-submit" type="submit" disabled>Search</button>
                    </div>
                  </form>
                  <div id="drive-search-results" class="results-list" aria-live="polite"></div>
                </section>
              </div>
            </div>
          </article>
          <article class="panel">
            <div class="panel-head"><span>agent access</span><span class="panel-meta">mcp</span></div>
            <div class="panel-body">
              <p id="mcp-status">Checking MCP setup...</p>
              <pre id="mcp-config" class="config-block hidden"></pre>
              <div class="row">
                <button id="mcp-test" class="ghost" type="button">Test MCP</button>
              </div>
              <p id="mcp-test-result" class="help"></p>
            </div>
          </article>
          <article class="panel">
            <div class="panel-head"><span>audit log</span><span class="panel-meta">proof</span></div>
            <div class="panel-body"><p id="audit-status">Checking audit log...</p></div>
          </article>
        </div>
      </section>
      <p id="error" role="alert"></p>
    </main>
    <script src="/assets/app.js" type="module"></script>
  </body>
</html>
`;

export const APP_CSS = `:root {
  color-scheme: dark;
  --bg: #0d0d0d;
  --panel: #161616;
  --panel-2: #1f1f1f;
  --line: rgba(255, 255, 255, 0.1);
  --line-strong: rgba(255, 255, 255, 0.16);
  --text: #fafafa;
  --muted: #a8a8a8;
  --faint: #737373;
  --accent: #fafafa;
  --accent-fg: #0d0d0d;
  --green: #9ab09a;
  --amber: #c0b080;
  --red: #d98585;
  font-family: Geist, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
}
body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at 20% 10%, rgba(255, 255, 255, 0.05), transparent 28rem),
    var(--bg);
}
*, *::before, *::after {
  box-sizing: border-box;
}
button, input, select {
  font: inherit;
}
.shell {
  max-width: 1100px;
  margin: 0 auto;
  padding: 30px 20px 40px;
}
.topbar {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 24px;
}
.eyebrow {
  margin: 0 0 4px;
  color: var(--faint);
  font: 11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-weight: 700;
  letter-spacing: 0;
  text-transform: uppercase;
}
h1, h2, p {
  margin-top: 0;
}
h1 {
  max-width: 13ch;
  margin-bottom: 10px;
  font-family: ui-serif, "New York", "Iowan Old Style", Palatino, Georgia, serif;
  font-size: clamp(34px, 6vw, 58px);
  font-weight: 400;
  line-height: 1.15;
}
h2 {
  margin-bottom: 10px;
  font-size: 24px;
  font-weight: 500;
}
.lede {
  max-width: 520px;
  color: var(--muted);
  font-size: 16px;
  line-height: 1.55;
}
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 12px;
}
.metrics {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
  margin-bottom: 12px;
}
.metric {
  min-height: 86px;
  padding: 14px;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 8px;
}
.metric strong {
  display: block;
  margin-top: 5px;
  overflow-wrap: anywhere;
  font-size: 20px;
  font-weight: 750;
}
.panel {
  overflow: hidden;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 8px;
  box-shadow: 0 18px 60px rgba(0, 0, 0, 0.22);
}
.wide {
  grid-column: 1 / -1;
}
.panel-head {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 12px 14px;
  border-bottom: 1px solid var(--line);
  background: var(--panel-2);
  color: var(--muted);
  font: 11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  text-transform: uppercase;
}
.panel-meta {
  margin-left: auto;
  color: var(--faint);
}
.panel-body {
  padding: 18px;
}
.login-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(320px, 420px);
  gap: 24px;
  align-items: start;
}
#login-form {
  display: grid;
  gap: 12px;
}
#login-form label {
  margin-bottom: -4px;
}
#login-submit {
  margin-top: 2px;
}
.row {
  display: flex;
  gap: 8px;
  align-items: stretch;
}
.retrieval-grid {
  display: grid;
  grid-template-columns: minmax(0, 0.9fr) minmax(0, 1.1fr);
  gap: 18px;
}
.search-form {
  display: grid;
  gap: 8px;
}
.dots {
  display: inline-flex;
  gap: 5px;
}
.dots span {
  width: 8px;
  height: 8px;
  border-radius: 999px;
  background: var(--faint);
  opacity: 0.65;
}
.label {
  color: var(--faint);
  font: 11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  text-transform: uppercase;
}
label {
  display: block;
  margin-bottom: 8px;
  color: var(--muted);
  font: 11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  text-transform: uppercase;
}
input, select {
  width: 100%;
  min-width: 0;
  border: 1px solid var(--line-strong);
  border-radius: 6px;
  padding: 10px;
  background: #101010;
  color: var(--text);
  font: 12px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
select {
  min-height: 42px;
  margin-top: 8px;
}
button, .button-link {
  border: 0;
  border-radius: 6px;
  padding: 10px 14px;
  background: var(--accent);
  color: var(--accent-fg);
  cursor: pointer;
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 42px;
  min-width: 0;
  line-height: 1.2;
  overflow-wrap: anywhere;
  text-align: center;
  white-space: normal;
  font-weight: 650;
}
button:hover:not(:disabled), .button-link:hover {
  background: #ffffff;
}
button:disabled {
  cursor: not-allowed;
  background: #2a2a2a;
  color: var(--faint);
  border: 1px solid var(--line);
}
.ghost {
  background: transparent;
  color: var(--muted);
  border: 1px solid var(--line-strong);
}
.ghost:hover:not(:disabled) {
  background: var(--panel-2);
  color: var(--text);
}
button:focus-visible,
.button-link:focus-visible,
input:focus-visible,
select:focus-visible {
  outline: 2px solid rgba(250, 250, 250, 0.42);
  outline-offset: 2px;
}
.hidden {
  display: none;
}
.help {
  margin: 8px 0 0;
  color: var(--faint);
  font-size: 12px;
}
.select-label {
  margin-top: 14px;
}
.results-list {
  display: grid;
  gap: 8px;
  margin-top: 12px;
}
.result-item {
  padding: 10px 12px;
  border: 1px solid var(--line);
  border-radius: 6px;
  background: #101010;
}
.result-title {
  margin: 0 0 5px;
  color: var(--text);
  font-weight: 650;
}
.result-snippet {
  margin: 0;
  color: var(--muted);
  font-size: 13px;
  line-height: 1.5;
}
.result-meta {
  margin-top: 8px;
  color: var(--faint);
  font: 11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
.notice {
  padding: 10px 12px;
  border: 1px solid rgba(192, 176, 128, 0.36);
  border-radius: 8px;
  background: rgba(192, 176, 128, 0.08);
  color: #dfd3a2;
}
.workspace-summary {
  margin: 0;
  padding: 10px 12px;
  border: 1px solid var(--line-strong);
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.045);
  color: var(--muted);
  font-size: 13px;
  line-height: 1.45;
}
.terminal-line {
  margin: 0;
  color: var(--muted);
  font: 12px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
.config-block {
  overflow: auto;
  max-width: 100%;
  margin: 12px 0;
  padding: 12px;
  border: 1px solid var(--line);
  border-radius: 6px;
  background: #101010;
  color: var(--muted);
  font: 12px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  line-height: 1.5;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
dl {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 8px 12px;
  margin: 0;
}
dt {
  color: var(--faint);
  font: 11px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  text-transform: uppercase;
}
dd {
  margin: 0;
  min-width: 0;
  overflow-wrap: anywhere;
}
#error {
  margin-top: 16px;
  padding: 10px 12px;
  border: 1px solid rgba(217, 133, 133, 0.34);
  border-radius: 8px;
  background: rgba(217, 133, 133, 0.1);
  color: #f0b0b0;
  font-weight: 600;
}
#error:empty {
  display: none;
}
@media (max-width: 640px) {
  .shell {
    padding: 24px 14px;
  }
  .topbar, .row, .login-grid, .retrieval-grid {
    align-items: stretch;
    flex-direction: column;
    display: flex;
  }
  .metrics {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
  button, .button-link {
    width: 100%;
  }
}
`;

export const APP_JS = `const $ = (id) => document.getElementById(id);
let csrfToken = "";
let refreshing = false;
let appConfig = { mode: "production", oauthConfigured: false, defaultWorkspaceId: null };
let driveFiles = [];
let driveRetrievalReady = false;

const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

const setError = (message = "") => {
  $("error").textContent = message;
};

const messageForError = (path, status, body) => {
  const code = body?.error;
  if (path.includes("/v1/auth/google/start")) {
    if (status === 400 || code === "invalid_workspace") return "Enter a valid workspace UUID.";
    if (status === 403 || code === "origin") return "This page was opened from an unexpected local address. Reload the dashboard and try again.";
    if (status === 503 || code === "misconfigured") return "Dashboard login is not configured for this environment.";
  }
  if (path.includes("/v1/connections/google-drive/start")) {
    if (status === 403 || code === "csrf") return "Refresh the page before connecting Drive.";
    if (status === 401) return "Sign in again before connecting Drive.";
    if (status === 503 || code === "misconfigured") return "Drive connection is not configured for this environment.";
  }
  if (path.includes("/v1/drive/")) {
    if (status === 403 || code === "csrf") return "Refresh the page before using Drive retrieval.";
    if (status === 401) return "Sign in again before using Drive retrieval.";
    if (status === 503 || code === "misconfigured") return "MCP is not configured for Drive retrieval.";
    if (body?.message) return body.message;
  }
  if (status === 401) return "Your session expired. Sign in again.";
  if (status >= 500) return "A Pact service is unavailable. Try again in a moment.";
  return body?.message || code || path + " returned " + status;
};

const requestJson = async (path, init = {}) => {
  const devHeaders = appConfig.mode !== "production" ? { "x-pact-local-dev": "1" } : {};
  const res = await fetch(path, {
    ...init,
    headers: {
      accept: "application/json",
      ...devHeaders,
      ...(init.headers ?? {}),
    },
  });
  if (!res.ok) {
    let body = null;
    try {
      body = await res.json();
    } catch {}
    throw new Error(messageForError(path, res.status, body));
  }
  return res.json();
};

const showView = (name) => {
  for (const id of ["loading", "login", "dashboard"]) {
    $(id).classList.toggle("hidden", id !== name);
  }
  $("logout").classList.toggle("hidden", name !== "dashboard");
};

const refreshSession = async () => {
  if (refreshing || !csrfToken) return false;
  refreshing = true;
  try {
    const res = await fetch("/v1/session/refresh", {
      method: "POST",
      headers: { "x-pact-csrf": csrfToken },
    });
    return res.ok;
  } finally {
    refreshing = false;
  }
};

const loadConfig = async () => {
  try {
    appConfig = await requestJson("/v1/config");
  } catch {}
  const workspaceInput = $("workspace-id");
  const workspaceField = $("workspace-field");
  const workspaceSummary = $("workspace-summary");
  const defaultWorkspaceId = appConfig.defaultWorkspaceId;
  if (defaultWorkspaceId && uuidPattern.test(defaultWorkspaceId)) {
    workspaceInput.value = defaultWorkspaceId;
    workspaceField.classList.add("hidden");
    workspaceSummary.classList.remove("hidden");
    workspaceSummary.textContent = "Demo workspace selected. Continue with Google to sign in.";
  } else {
    const lastWorkspaceId = window.localStorage.getItem("pact:lastWorkspaceId") || "";
    if (!workspaceInput.value && uuidPattern.test(lastWorkspaceId)) {
      workspaceInput.value = lastWorkspaceId;
    }
    workspaceField.classList.remove("hidden");
    workspaceSummary.classList.add("hidden");
  }
  const oauthHelp = $("oauth-help");
  if (!appConfig.oauthConfigured) {
    oauthHelp.classList.remove("hidden");
    oauthHelp.textContent =
      "Google OAuth credentials are not configured for this dashboard environment.";
  } else {
    oauthHelp.classList.add("hidden");
  }
};

const renderSession = (session) => {
  $("metric-workspace").textContent = session.workspaceId ?? "-";
  const details = $("session-details");
  const claims = session.claims ?? {};
  details.innerHTML = "";
  for (const [label, value] of [
    ["Workspace", session.workspaceId],
    ["Email", claims.email],
    ["Roles", Array.isArray(claims.roles) ? claims.roles.join(", ") : ""],
  ]) {
    const dt = document.createElement("dt");
    dt.textContent = label;
    const dd = document.createElement("dd");
    dd.textContent = value || "Unknown";
    details.append(dt, dd);
  }
};

const selectedDriveFile = () => {
  const fileId = $("drive-files").value;
  return driveFiles.find((file) => file.id === fileId) || null;
};

const renderDriveFileOptions = (files) => {
  driveFiles = files;
  const select = $("drive-files");
  select.innerHTML = "";
  if (!files.length) {
    const option = document.createElement("option");
    option.value = "";
    option.textContent = driveRetrievalReady ? "No files returned" : "Connect Drive and load files";
    select.append(option);
  } else {
    for (const file of files) {
      const option = document.createElement("option");
      option.value = file.id;
      option.textContent = file.name || file.id;
      select.append(option);
    }
  }
  select.disabled = !driveRetrievalReady || !files.length;
  $("drive-index").disabled = !driveRetrievalReady || !files.length;
};

const renderDriveRetrievalState = (driveStatus, mcp) => {
  driveRetrievalReady = driveStatus === "connected" && !!mcp?.configured && !!mcp?.endpoint;
  $("drive-files-refresh").disabled = !driveRetrievalReady;
  $("drive-search-submit").disabled = !driveRetrievalReady;
  $("drive-search-query").disabled = !driveRetrievalReady;
  if (!driveRetrievalReady) {
    renderDriveFileOptions([]);
    $("drive-index-result").textContent =
      driveStatus === "connected"
        ? "MCP must be configured before indexing Drive files."
        : "Connect Drive before indexing files.";
    $("drive-search-results").textContent = "";
    return;
  }
  if (!driveFiles.length) renderDriveFileOptions([]);
};

const renderSearchResults = (results) => {
  const container = $("drive-search-results");
  container.innerHTML = "";
  if (!results.length) {
    const empty = document.createElement("p");
    empty.className = "help";
    empty.textContent = "No indexed chunks matched this query.";
    container.append(empty);
    return;
  }
  for (const result of results) {
    const item = document.createElement("article");
    item.className = "result-item";
    const title = document.createElement("p");
    title.className = "result-title";
    title.textContent = result.fileName || result.fileId || "Drive file";
    const snippet = document.createElement("p");
    snippet.className = "result-snippet";
    snippet.textContent = result.snippet || "";
    const meta = document.createElement("p");
    meta.className = "result-meta";
    meta.textContent =
      "chunk " +
      (result.chunkIndex ?? "-") +
      (result.indexedAt ? " / indexed " + result.indexedAt : "");
    item.append(title, snippet, meta);
    container.append(item);
  }
};

const renderStatus = (status) => {
  const drive = status.connections?.drive;
  $("metric-users").textContent = String(status.users?.count ?? 0);
  const driveStatus = drive?.status || "unknown";
  $("metric-drive").textContent = driveStatus === "not_configured" ? "not set" : driveStatus;
  $("metric-audit").textContent = status.audit?.head ? "active" : "no head";
  $("drive-status").textContent =
    driveStatus === "not_configured"
      ? "Drive is not connected yet."
      : driveStatus === "connected"
        ? "Drive connected for " + (drive.email || "this user") + "."
        : "Drive connection status: " + driveStatus;
  $("drive-connect").textContent = driveStatus === "connected" ? "Reconnect Drive" : "Connect Drive";
  $("drive-connect").disabled = false;
  const canDisconnect = !["not_configured", "unknown", "disconnected"].includes(driveStatus);
  $("drive-disconnect").classList.toggle("hidden", !canDisconnect);
  $("drive-disconnect").disabled = !canDisconnect;
  renderMcpStatus(status.mcp, driveStatus);
  renderDriveRetrievalState(driveStatus, status.mcp);
  $("audit-status").textContent = status.audit?.head
    ? "Audit log is receiving signed events."
    : "No audit log checkpoint found yet.";
};

const renderMcpStatus = (mcp, driveStatus) => {
  const config = $("mcp-config");
  const test = $("mcp-test");
  $("mcp-test-result").textContent = "";
  if (!mcp?.configured || !mcp.endpoint) {
    $("mcp-status").textContent = "MCP server URL is not configured for this dashboard.";
    config.classList.add("hidden");
    test.disabled = true;
    return;
  }
  $("mcp-status").textContent =
    driveStatus === "connected"
      ? "MCP is ready for this workspace. Test the signed session before using Drive tools."
      : "MCP is configured. Connect Drive before using Drive tools.";
  config.textContent =
    "endpoint: " + mcp.endpoint + "\\\\n" + "audience: " + (mcp.audience || "pact-mcp");
  config.classList.remove("hidden");
  test.disabled = false;
};

const renderStatusUnavailable = (message) => {
  $("metric-users").textContent = "-";
  $("metric-drive").textContent = "unavailable";
  $("metric-audit").textContent = "unavailable";
  $("drive-status").textContent = "Connection status is unavailable.";
  $("drive-connect").disabled = false;
  $("drive-disconnect").classList.add("hidden");
  $("drive-disconnect").disabled = true;
  $("mcp-status").textContent = "Agent access status is unavailable.";
  $("mcp-config").classList.add("hidden");
  $("mcp-test").disabled = true;
  $("mcp-test-result").textContent = "";
  driveRetrievalReady = false;
  renderDriveFileOptions([]);
  $("drive-files-refresh").disabled = true;
  $("drive-search-submit").disabled = true;
  $("drive-search-query").disabled = true;
  $("drive-index-result").textContent = "Workspace status is unavailable.";
  $("drive-search-results").textContent = "";
  $("audit-status").textContent = message || "Audit log status is unavailable.";
};

const load = async () => {
  setError();
  await loadConfig();
  showView("loading");
  const session = await requestJson("/v1/session");
  if (!session.authenticated) {
    showView("login");
    return;
  }
  showView("dashboard");
  csrfToken = session.csrfToken ?? "";
  renderSession(session);
  try {
    renderStatus(await requestJson("/v1/workspace/status"));
  } catch (error) {
    if (await refreshSession()) {
      renderStatus(await requestJson("/v1/workspace/status"));
      return;
    }
    const message = error instanceof Error ? error.message : "Workspace status failed";
    renderStatusUnavailable(message);
    setError(message);
  }
};

$("login-form").addEventListener("submit", async (event) => {
  event.preventDefault();
  setError();
  const form = event.currentTarget;
  const workspaceId = String(new FormData(form).get("workspaceId") ?? "").trim();
  if (!uuidPattern.test(workspaceId)) {
    setError("Enter a valid workspace UUID.");
    $("workspace-id").focus();
    return;
  }
  window.localStorage.setItem("pact:lastWorkspaceId", workspaceId);
  const input = $("workspace-id");
  const button = $("login-submit");
  input.disabled = true;
  button.disabled = true;
  button.textContent = "Redirecting to Google...";
  try {
    const body = await requestJson("/v1/auth/google/start", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ workspaceId }),
    });
    window.location.href = body.location;
  } catch (error) {
    input.disabled = false;
    button.disabled = false;
    button.textContent = "Continue with Google";
    setError(error instanceof Error ? error.message : "Login failed");
  }
});

$("logout").addEventListener("click", async () => {
  await fetch("/v1/session", { method: "DELETE", headers: { "x-pact-csrf": csrfToken } });
  await load();
});

$("drive-connect").addEventListener("click", async () => {
  setError();
  const button = $("drive-connect");
  button.disabled = true;
  const previous = button.textContent;
  button.textContent = "Redirecting to Google...";
  try {
    const body = await requestJson("/v1/connections/google-drive/start", {
      method: "POST",
      headers: { "x-pact-csrf": csrfToken },
    });
    window.location.href = body.location;
  } catch (error) {
    button.disabled = false;
    button.textContent = previous || "Connect Drive";
    setError(error instanceof Error ? error.message : "Drive connection failed");
  }
});

$("drive-disconnect").addEventListener("click", async () => {
  setError();
  const button = $("drive-disconnect");
  button.disabled = true;
  try {
    await requestJson("/v1/connections/google-drive", {
      method: "DELETE",
      headers: { "x-pact-csrf": csrfToken },
    });
    await load();
  } catch (error) {
    button.disabled = false;
    setError(error instanceof Error ? error.message : "Drive disconnect failed");
  }
});

$("drive-files-refresh").addEventListener("click", async () => {
  setError();
  const button = $("drive-files-refresh");
  const result = $("drive-index-result");
  button.disabled = true;
  result.textContent = "Loading Drive files...";
  try {
    const body = await requestJson("/v1/drive/files", {
      method: "POST",
      headers: { "content-type": "application/json", "x-pact-csrf": csrfToken },
      body: JSON.stringify({ pageSize: 10 }),
    });
    renderDriveFileOptions(body.files || []);
    result.textContent = body.files?.length
      ? "Select a file and index it for MCP search."
      : "No Drive files were returned for this account.";
  } catch (error) {
    result.textContent = "";
    setError(error instanceof Error ? error.message : "Drive file list failed");
  } finally {
    button.disabled = !driveRetrievalReady;
  }
});

$("drive-index").addEventListener("click", async () => {
  setError();
  const file = selectedDriveFile();
  if (!file) {
    setError("Choose a Drive file to index.");
    return;
  }
  const button = $("drive-index");
  const result = $("drive-index-result");
  button.disabled = true;
  result.textContent = "Indexing " + (file.name || file.id) + "...";
  try {
    const body = await requestJson("/v1/drive/index", {
      method: "POST",
      headers: { "content-type": "application/json", "x-pact-csrf": csrfToken },
      body: JSON.stringify({
        fileId: file.id,
        fileName: file.name,
        modifiedTime: file.modifiedTime,
      }),
    });
    result.textContent =
      "Indexed " +
      (body.fileName || file.name || body.fileId) +
      " into " +
      body.chunks +
      " chunks" +
      (body.truncated ? " (truncated)." : ".");
  } catch (error) {
    result.textContent = "";
    setError(error instanceof Error ? error.message : "Drive indexing failed");
  } finally {
    button.disabled = !driveRetrievalReady || !driveFiles.length;
  }
});

$("drive-search-form").addEventListener("submit", async (event) => {
  event.preventDefault();
  setError();
  const query = String(new FormData(event.currentTarget).get("query") || "").trim();
  if (!query) {
    setError("Enter a Drive search query.");
    $("drive-search-query").focus();
    return;
  }
  const button = $("drive-search-submit");
  button.disabled = true;
  $("drive-search-results").textContent = "Searching indexed Drive context...";
  try {
    const body = await requestJson("/v1/drive/search", {
      method: "POST",
      headers: { "content-type": "application/json", "x-pact-csrf": csrfToken },
      body: JSON.stringify({ query, limit: 5 }),
    });
    renderSearchResults(body.results || []);
  } catch (error) {
    $("drive-search-results").textContent = "";
    setError(error instanceof Error ? error.message : "Drive search failed");
  } finally {
    button.disabled = !driveRetrievalReady;
  }
});

$("mcp-test").addEventListener("click", async () => {
  setError();
  const button = $("mcp-test");
  const result = $("mcp-test-result");
  button.disabled = true;
  result.textContent = "Testing MCP...";
  try {
    const body = await requestJson("/v1/mcp/test", {
      method: "POST",
      headers: { "x-pact-csrf": csrfToken },
    });
    if (body.response?.error) {
      result.textContent =
        "MCP denied the test call: " +
        (body.response.error.message || body.response.error.code || "unknown error");
    } else {
      result.textContent = "MCP test passed with pact.whoami.";
    }
  } catch (error) {
    result.textContent = "";
    setError(error instanceof Error ? error.message : "MCP test failed");
  } finally {
    button.disabled = false;
  }
});

load().catch((error) => {
  showView("login");
  setError(error instanceof Error ? error.message : "Dashboard failed");
});
`;
