-- Ensure the agents.kind enum is enforced by a named DB CHECK constraint.
-- Migration 0024 declared an inline (anonymous) CHECK whose autogenerated
-- name follows Postgres convention (agents_kind_check). Adding it explicitly
-- here makes the contract explicit, keeps drizzle schema and DB in sync, and
-- guards against future migrations or ad-hoc inserts drifting from the enum.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'agents' AND constraint_name = 'agents_kind_check'
  ) THEN
    ALTER TABLE agents ADD CONSTRAINT agents_kind_check
      CHECK (kind IN ('service', 'user_delegated', 'sub_agent'));
  END IF;
END$$;
